### ISSUE TITLE
Fake

### ISSUE THREAD

**Issue by rgaricano** [Open-Source-O1/Open-O1#1]
Are you kidding us?

there isn't any model there, the model that are linked on running app is gpt4

\`\`\`
I'm OpenAI's GPT-4, the latest version of our advanced language generation model. I'm designed to handle a variety of tasks, from answering questions and translating languages to assisting with writing and more. How can I help you today?
\`\`\`
```
from V3 import call_gpt
...
    def ask(self, history, prompt):
        history = self.pop_history(history)
        logger.info(history)
        return call_gpt(history, prompt)
```

**Comment by OpenSource-O1** [comment]
Hello, thank you for your feedback! Firstly, we should clarify that our OpenO1 model does not incorporate any aspects of GPT-4. It is built on LLaMA and Qwen, and we are not using the GPT-4 API in any capacity.

Then, for reference, you can check our model on Hugging Face: https://huggingface.co/O1-OPEN/OpenO1-Qwen-7B-v0.1;
https://huggingface.co/O1-OPEN/OpenO1-LLama-8B-v0.1.

And could you share how you are operating or interacting with the application? Any specific steps or actions you've taken would be helpful for us to understand your experience better.
